name: ci

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  PROJECT_PATH: exo-holdout
  EXPORT_NAME: Exo Holdout
  GODOT_VERSION: 4.6

permissions:
  id-token: write
  contents: read

jobs:
  login-to-amazon-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::683497281432:role/github-oidc-role-Role-NtZAFHaKjamQ
          aws-region: us-east-1
          audience: sts.amazonaws.com
          mask-aws-account-id: "false"
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "false"
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
      docker_username: ${{ steps.login-ecr.outputs.docker_username_683497281432_dkr_ecr_us_east_1_amazonaws_com }}
      docker_password: ${{ steps.login-ecr.outputs.docker_password_683497281432_dkr_ecr_us_east_1_amazonaws_com }}

  godot-build:
    needs: login-to-amazon-ecr
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.login-to-amazon-ecr.outputs.registry }}/skg/godot:4.6-stable
      credentials:
        username: ${{ needs.login-to-amazon-ecr.outputs.docker_username }}
        password: ${{ needs.login-to-amazon-ecr.outputs.docker_password }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Lint GDScripts
        run: |
          gdlint scripts/.
